DETECTION_TYPES = [
    'TYPE_UNSPECIFIED',
    'FACE_DETECTION',
    'LANDMARK_DETECTION',
    'LOGO_DETECTION',
    'LABEL_DETECTION',
    'TEXT_DETECTION',
    'SAFE_SEARCH_DETECTION',
]

DETECTION_TYPES_ABBR = {
    'F': 'FACE_DETECTION',
    'LM': 'LANDMARK_DETECTION',
    'LO': 'LOGO_DETECTION',
    'LA': 'LABEL_DETECTION',
    'T': 'TEXT_DETECTION',
    'S': 'SAFE_SEARCH_DETECTION',
}
